{
  "formatVersion": "1.1",
  "component": {
    "group": "io.liveness.flash",
    "module": "sdk-android",
    "version": "v1.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 211368,
          "sha512": "1da2a56bd62732bf769f0a5cadcaa36e8243329ea8187aeabc583c0593a74c3bc38677d98b0c43b8131edda37f6f98ab4850b1fe2cbad6415059e05cd99902de",
          "sha256": "9dd1b74a5598b2b506cadd0079c7a8163b66a995d318d64c28bc8b8fe1ad860a",
          "sha1": "5c5c59a93a20d9eb968877a04739ac3b8bf8120a",
          "md5": "4252330684122c102b36882c849333b3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "face-detection",
          "version": {
            "requires": "16.1.5"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.65"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.31"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.trustvision",
          "module": "tv_sdk",
          "version": {
            "requires": "2.1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 211368,
          "sha512": "1da2a56bd62732bf769f0a5cadcaa36e8243329ea8187aeabc583c0593a74c3bc38677d98b0c43b8131edda37f6f98ab4850b1fe2cbad6415059e05cd99902de",
          "sha256": "9dd1b74a5598b2b506cadd0079c7a8163b66a995d318d64c28bc8b8fe1ad860a",
          "sha1": "5c5c59a93a20d9eb968877a04739ac3b8bf8120a",
          "md5": "4252330684122c102b36882c849333b3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-android-v1.1.9-sources.jar",
          "url": "sdk-android-v1.1.9-sources.jar",
          "size": 80968,
          "sha512": "5510357162cd23ad0b7c20ea27a207666d63b7bd74e428453bc2cb63b6d8e815972af02e9a30c1d5966287c9a7d71e7a8037e020c0abdae040eb957d1f522e2d",
          "sha256": "2db6663758826b393425d10cc42ee825f121fba20309c5575e955fe9808dd14e",
          "sha1": "89b6f2e0c76762784af9685b0e6d4020dd91a795",
          "md5": "7a9b90de25114adba6e24c5e6329ae77"
        }
      ]
    }
  ]
}
