{
  "formatVersion": "1.1",
  "component": {
    "group": "io.liveness.flash",
    "module": "sdk-android",
    "version": "v1.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 209693,
          "sha512": "b646624c2055a4e3998e05af1e1ac0aaaa04901d14aa3547bb4c982001056f1959eaff593a49844cc39c2a18b518780e1d86077e69f61368885773ae4c6ce760",
          "sha256": "8c49a5ec54d639b3c796f8e7a4336e54f3a81bfed11f2786ae98aa77068eae46",
          "sha1": "545cd03027d7d0e759b167c22af2c58f14d7f610",
          "md5": "91eedaa8f87d29d0b7c0a8686ce98dc8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "face-detection",
          "version": {
            "requires": "16.1.5"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.65"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.31"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.trustvision",
          "module": "tv_sdk",
          "version": {
            "requires": "2.1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 209693,
          "sha512": "b646624c2055a4e3998e05af1e1ac0aaaa04901d14aa3547bb4c982001056f1959eaff593a49844cc39c2a18b518780e1d86077e69f61368885773ae4c6ce760",
          "sha256": "8c49a5ec54d639b3c796f8e7a4336e54f3a81bfed11f2786ae98aa77068eae46",
          "sha1": "545cd03027d7d0e759b167c22af2c58f14d7f610",
          "md5": "91eedaa8f87d29d0b7c0a8686ce98dc8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-android-v1.1.9-sources.jar",
          "url": "sdk-android-v1.1.9-sources.jar",
          "size": 80327,
          "sha512": "9a36f3d5c5783259e4a0d5f70e9fb66aed78a58f3d99c26eac8a293a9eafb6211846ee00ee22083835a3f435561d3d07d5d156f5fae7d2a2c36095eef9c75b3f",
          "sha256": "797c14ef7ae35c419fed93befbd69c7378486eb852031fd087234c3f107f0c69",
          "sha1": "863b3409d9a91d3a4d5efd0c9f0274add00159d4",
          "md5": "ab7b1151b80caa93d234265a75e07489"
        }
      ]
    }
  ]
}
