{
  "formatVersion": "1.1",
  "component": {
    "group": "io.liveness.flash",
    "module": "sdk-android",
    "version": "v1.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 210041,
          "sha512": "427611d5d775c8759a37ae874123bc7c5b11a30569cfc1edaaa1e67fdc9aa617cbd10823861581276e2400d41a9d9074b643afb480a451df1656a1f3d2619bed",
          "sha256": "d3be0d377f2ea917a7b6087c85a17bfed8dffc893f794fff42401a35afd514c2",
          "sha1": "df17247f8a3eefee500af52445b562889567c39b",
          "md5": "43318cd27db813b9735dafbcb8f33c82"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "face-detection",
          "version": {
            "requires": "16.1.5"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.65"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.31"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.trustvision",
          "module": "tv_sdk",
          "version": {
            "requires": "2.1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 210041,
          "sha512": "427611d5d775c8759a37ae874123bc7c5b11a30569cfc1edaaa1e67fdc9aa617cbd10823861581276e2400d41a9d9074b643afb480a451df1656a1f3d2619bed",
          "sha256": "d3be0d377f2ea917a7b6087c85a17bfed8dffc893f794fff42401a35afd514c2",
          "sha1": "df17247f8a3eefee500af52445b562889567c39b",
          "md5": "43318cd27db813b9735dafbcb8f33c82"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-android-v1.1.9-sources.jar",
          "url": "sdk-android-v1.1.9-sources.jar",
          "size": 80384,
          "sha512": "12434473d9b0726db160c7d9494a58ae1545b6242f4360ebd00b8429022a2e25388fb7bc590b0f8b335fb2d110cfd0524976c485b8e8a1ebdc638a6d97541678",
          "sha256": "9d869531b78c92da85f243e9da38bad8632123a093e859f7f0a563ea6969bf35",
          "sha1": "de9919d01cd0e42076832ffe5d702efdcd9885c5",
          "md5": "d6768d974c1acafaf56418deed2bc905"
        }
      ]
    }
  ]
}
