{
  "formatVersion": "1.1",
  "component": {
    "group": "com.son.sdk",
    "module": "ekycplugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.6.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.6.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.6.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.6.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ekycplugin-1.0.0.aar",
          "url": "ekycplugin-1.0.0.aar",
          "size": 74069848,
          "sha512": "02e0314e700f1922c326931b236210aa6bc5147848e01f41ad306a2a45c2642f99956705349baa227ac1340c5f46db269fc538826443a4a869f8dd391b640e60",
          "sha256": "5621a86e3cd5668130a6f6362258d34533afa4ab380a5f4299ea6ce8da9086d0",
          "sha1": "d724958ed87db81e4e9f50ec44bd2949d0d48912",
          "md5": "5cd9306506c8b99a8f324557ab1d9f35"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.tensorflow",
          "module": "tensorflow-lite",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.tensorflow",
          "module": "tensorflow-lite-support",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "face-detection",
          "version": {
            "requires": "16.1.6"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.opencv",
          "module": "opencv",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.6.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.6.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.6.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.6.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ekycplugin-1.0.0.aar",
          "url": "ekycplugin-1.0.0.aar",
          "size": 74069848,
          "sha512": "02e0314e700f1922c326931b236210aa6bc5147848e01f41ad306a2a45c2642f99956705349baa227ac1340c5f46db269fc538826443a4a869f8dd391b640e60",
          "sha256": "5621a86e3cd5668130a6f6362258d34533afa4ab380a5f4299ea6ce8da9086d0",
          "sha1": "d724958ed87db81e4e9f50ec44bd2949d0d48912",
          "md5": "5cd9306506c8b99a8f324557ab1d9f35"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ekycplugin-1.0.0-sources.jar",
          "url": "ekycplugin-1.0.0-sources.jar",
          "size": 336431,
          "sha512": "ca3b6e2240b28517f46fc7848f920a05ecc15aae2d4edc79d692d3000a1d9d0391d3d0b0953a1f46269c1b18e932a2a54d0002addfae388d5d6f2f19d72cae58",
          "sha256": "4af89c7c98c75617cc86b41154d847549333d347a0bbc40850c61447d90875ca",
          "sha1": "d802657ed69b34696c61b053aefcc6c6b95783b9",
          "md5": "ca5910fecb37dd1297a0767180a56d4a"
        }
      ]
    }
  ]
}
