{
  "formatVersion": "1.1",
  "component": {
    "group": "io.liveness.flash",
    "module": "sdk-android",
    "version": "v1.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 246499,
          "sha512": "f786b99fed0ff220b0f2de5376de11b720a935d84ca8662ae09f8c56d436805faf585dcb9b6ff1d270efa8f194a9cc4384df914167b2dc34319850e4bc8a80cb",
          "sha256": "91303efa63de687d826760f55e69fe2749ccc7a54b35b387c3517b56f4896078",
          "sha1": "c5eab58aeec8b1aa4ebe7fed0fe6241d8cf1379d",
          "md5": "b33476f7f4bfa0e02880977e1bdc8250"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "face-detection",
          "version": {
            "requires": "16.1.5"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.65"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.31"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.trustvision",
          "module": "tv_sdk",
          "version": {
            "requires": "2.1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 246499,
          "sha512": "f786b99fed0ff220b0f2de5376de11b720a935d84ca8662ae09f8c56d436805faf585dcb9b6ff1d270efa8f194a9cc4384df914167b2dc34319850e4bc8a80cb",
          "sha256": "91303efa63de687d826760f55e69fe2749ccc7a54b35b387c3517b56f4896078",
          "sha1": "c5eab58aeec8b1aa4ebe7fed0fe6241d8cf1379d",
          "md5": "b33476f7f4bfa0e02880977e1bdc8250"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-android-v1.1.9-sources.jar",
          "url": "sdk-android-v1.1.9-sources.jar",
          "size": 70441,
          "sha512": "c22edb5c9e46e6b63f25d50275c6c0c71d383d7fac1b5a1be145f0ce3e2efbd2b6f77c78532ae215b83e8f2faae5bfdf541c2eba3acaf22fc014ef1a993cc6c3",
          "sha256": "ed24a09f4cf3f7058161730258e914dd9276f428312834b02e65750acd6b8cf1",
          "sha1": "e04ea7b5bf10e962e9c7f5dd023eee4a35cea019",
          "md5": "3ccb31cbccb2557fe1af94a10ccadf37"
        }
      ]
    }
  ]
}
