{
  "formatVersion": "1.1",
  "component": {
    "group": "io.liveness.flash",
    "module": "sdk-android",
    "version": "v1.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 209733,
          "sha512": "b6cf09d1b5bc15d0845e7276fbaf6f8c456cd98528e41167994ac4b72f21ad738d87d4cd2bb4acfb054a058a450bacbe66047f2f91351250f5f2c2b1cd735c5d",
          "sha256": "bb32f173c512422a8b15ba1a8fc41ece6d6a0262312f3634827068ecef422f9d",
          "sha1": "cc74e49de4d7c058ba6e472e7411215a53dc3e60",
          "md5": "ddfa3a8bd0fcf881cfe748d7258f9a5c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "face-detection",
          "version": {
            "requires": "16.1.5"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.65"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.31"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.trustvision",
          "module": "tv_sdk",
          "version": {
            "requires": "2.1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 209733,
          "sha512": "b6cf09d1b5bc15d0845e7276fbaf6f8c456cd98528e41167994ac4b72f21ad738d87d4cd2bb4acfb054a058a450bacbe66047f2f91351250f5f2c2b1cd735c5d",
          "sha256": "bb32f173c512422a8b15ba1a8fc41ece6d6a0262312f3634827068ecef422f9d",
          "sha1": "cc74e49de4d7c058ba6e472e7411215a53dc3e60",
          "md5": "ddfa3a8bd0fcf881cfe748d7258f9a5c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-android-v1.1.9-sources.jar",
          "url": "sdk-android-v1.1.9-sources.jar",
          "size": 80164,
          "sha512": "309c47b9b2d0a6f072e9ad83c2c3532790d657d427a20ad4f387aff80217a6ef45eb9c2932ccf3c2ed5718533495bed60c09c67667a92bd1e9d6b02884f4bed3",
          "sha256": "45dc73c04c68ce466facc98eebbfae750242d2135437547cd9c88fb5e64a9841",
          "sha1": "f5115e3eb8943dd8cdfbffbf4e8bf2a9ac982f28",
          "md5": "0657155730fa8fdce1aee6420756a719"
        }
      ]
    }
  ]
}
