{
  "formatVersion": "1.1",
  "component": {
    "group": "io.liveness.flash",
    "module": "sdk-android",
    "version": "v1.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 210660,
          "sha512": "fbb85d7b9ee5c82b72bb06d3d1f2f2ccef6b4f775aeb2d1e24f258a78d29f9ac66f318c1737e34466c73c25a5e1b5e0c0124ecd520c32a744261fa2847175851",
          "sha256": "f3b95337126c0f5b3fbb2f462c34e62278e9b72a4b8496cef973a10a2b218894",
          "sha1": "33f1a878fece1b3bd338f027dc309ab22cd182a2",
          "md5": "37ae5467fa7c7ec1e526d25c1e37aad8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "face-detection",
          "version": {
            "requires": "16.1.5"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.65"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.31"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.trustvision",
          "module": "tv_sdk",
          "version": {
            "requires": "2.1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 210660,
          "sha512": "fbb85d7b9ee5c82b72bb06d3d1f2f2ccef6b4f775aeb2d1e24f258a78d29f9ac66f318c1737e34466c73c25a5e1b5e0c0124ecd520c32a744261fa2847175851",
          "sha256": "f3b95337126c0f5b3fbb2f462c34e62278e9b72a4b8496cef973a10a2b218894",
          "sha1": "33f1a878fece1b3bd338f027dc309ab22cd182a2",
          "md5": "37ae5467fa7c7ec1e526d25c1e37aad8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-android-v1.1.9-sources.jar",
          "url": "sdk-android-v1.1.9-sources.jar",
          "size": 80558,
          "sha512": "fcdad74af5cade442aab56a2482e78e9411299bdfdda0f8caefb9006495815448da3253e38491e7c267ec7cc789442b1c7168c327f2e91625325fc9a5ad85de3",
          "sha256": "c84ae511b3fd705bf315ab2a9d509e1f0ce09856487bb0969980bfb82cb36c7c",
          "sha1": "ad250ca0916c403dd17ccca129eaeda58b48c1c3",
          "md5": "66fdc937e5b5ba2990c5d864b3e79d54"
        }
      ]
    }
  ]
}
